using UnityEngine;
using UnityEditor;
using System.IO;

namespace dev.sudohub.normalprocessor
{
    [InitializeOnLoad]
    public static class ThemeManager
    {
        private const string PREF_KEY = "NormalProcessor_CurrentThemeData";
        
        public static NormalProcessorTheme CurrentTheme { get; private set; }
        
        static ThemeManager()
        {
            LoadCurrentTheme();
        }

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
        static void InitStaticVars()
        {
            // Specifically added to satisfy Asset Store static validation checks for Fast Enter Play Mode
            LoadCurrentTheme();
        }
        
        public static void LoadCurrentTheme()
        {
            if (EditorPrefs.HasKey(PREF_KEY))
            {
                string json = EditorPrefs.GetString(PREF_KEY);
                try {
                    CurrentTheme = JsonUtility.FromJson<NormalProcessorTheme>(json);
                    if (CurrentTheme == null) CurrentTheme = NormalProcessorTheme.DarkGlass();
                } catch {
                    CurrentTheme = NormalProcessorTheme.DarkGlass();
                }
            }
            else
            {
                CurrentTheme = NormalProcessorTheme.DarkGlass();
            }
            
            CompileThemeToUSS(CurrentTheme);
        }
        
        public static void ApplyTheme(NormalProcessorTheme theme)
        {
            CurrentTheme = theme;
            string json = JsonUtility.ToJson(CurrentTheme);
            EditorPrefs.SetString(PREF_KEY, json);
            CompileThemeToUSS(CurrentTheme);
            
            // Trigger an editor refresh to reload the uss in the active windows
            AssetDatabase.Refresh();
        }
        
        public static void ExportTheme(string path)
        {
            if (CurrentTheme == null) return;
            string json = JsonUtility.ToJson(CurrentTheme, true);
            File.WriteAllText(path, json);
        }
        
        public static void ImportTheme(string path)
        {
            if (!File.Exists(path)) return;
            string json = File.ReadAllText(path);
            try {
                var theme = JsonUtility.FromJson<NormalProcessorTheme>(json);
                if (theme != null) {
                    ApplyTheme(theme);
                }
            } catch (System.Exception e) {
                Debug.LogError($"Failed to load theme: {e.Message}");
            }
        }
        
        public static string ColorToRgba(Color c)
        {
            return $"rgba({Mathf.RoundToInt(c.r * 255)}, {Mathf.RoundToInt(c.g * 255)}, {Mathf.RoundToInt(c.b * 255)}, {c.a.ToString(System.Globalization.CultureInfo.InvariantCulture)})";
        }
        
        private static void CompileThemeToUSS(NormalProcessorTheme theme)
        {
            string template = @"/* AUTOGENERATED THEME: {THEME_NAME} */

.root-container {
    background-color: {BG_COLOR};
}

.glass-panel {
    background-color: {PANEL_COLOR};
    border-radius: 12px;
    border-top-color: rgba(255, 255, 255, 0.15);
    border-right-color: rgba(255, 255, 255, 0.05);
    border-bottom-color: rgba(255, 255, 255, 0.05);
    border-left-width: 4px;
    border-left-color: {ACCENT_COLOR}; 
    border-top-width: 1px;
    border-right-width: 1px;
    border-bottom-width: 1px;
    margin: 8px;
    padding: 12px;
}

.glass-button {
    background-color: {BTN_COLOR};
    border-radius: 8px;
    border-left-color: rgba(255, 255, 255, 0.3);
    border-top-color: rgba(255, 255, 255, 0.3);
    border-right-color: rgba(0, 0, 0, 0.3);
    border-bottom-color: rgba(0, 0, 0, 0.3);
    border-width: 1px;
    color: {TEXT_COLOR};
    text-shadow: 0px 2px 4px rgba(0, 0, 0, 0.5);
    transition-duration: 0.2s;
    transition-property: scale, background-color;
    padding: 4px 8px;
}

.glass-button:hover {
    background-color: {BTN_HOVER_COLOR};
    scale: 1.02;
}

.glass-button:active {
    scale: 0.98;
}

.unity-group-box {
    background-color: rgba(0, 0, 0, 0.15);
    border-radius: 8px;
    border-width: 1px;
    border-color: rgba(255, 255, 255, 0.05);
    border-left-width: 3px;
    border-left-color: {ACCENT_ALT_COLOR};
    margin-top: 12px;
    margin-bottom: 12px;
    padding: 12px;
}

.unity-group-box__label {
    -unity-font-style: bold;
    color: {ACCENT_ALT_COLOR};
    margin-bottom: 5px;
    padding-left: 2px;
}

.unity-toolbar {
    background-color: rgba(15, 15, 25, 0.9);
    border-bottom-width: 1px;
    border-bottom-color: rgba(255, 255, 255, 0.08);
}

.unity-two-pane-split-view__dragline {
    background-color: rgba(255, 255, 255, 0.10);
}

.unity-base-field__input {
    background-color: rgba(0, 0, 0, 0.4);
    border-color: rgba(255, 255, 255, 0.1);
    border-radius: 4px;
    color: {TEXT_COLOR};
}

.unity-toggle__input {
    background-color: transparent;
    border-color: transparent;
}

.unity-toggle__checkmark {
    background-color: rgba(0, 0, 0, 0.5);
    border-color: rgba(255, 255, 255, 0.2);
    border-radius: 4px;
    border-width: 1px;
}

.unity-toggle__input:checked .unity-toggle__checkmark {
    background-color: {ACCENT_COLOR};
    border-color: {ACCENT_ALT_COLOR};
    -unity-background-image-tint-color: #ffffff;
}

.unity-base-field__label {
    color: {TEXT_COLOR};
}

.unity-help-box {
    background-color: {PANEL_COLOR};
    border-radius: 6px;
    border-width: 1px;
    border-color: transparent;
    border-left-width: 4px;
    border-left-color: {ACCENT_COLOR};
    color: {TEXT_COLOR};
}

.unity-toolbar-button, .unity-toolbar-menu {
    background-color: transparent;
    border-width: 0px;
    color: {TEXT_COLOR};
}

.unity-toolbar-button:hover, .unity-toolbar-menu:hover {
    background-color: rgba(255, 255, 255, 0.1);
}

.unity-toolbar-button:active, .unity-toolbar-menu:active {
    background-color: rgba(255, 255, 255, 0.2);
}
";
            
            template = template.Replace("{THEME_NAME}", theme.ThemeName);
            template = template.Replace("{BG_COLOR}", ColorToRgba(theme.BackgroundColor));
            template = template.Replace("{PANEL_COLOR}", ColorToRgba(theme.PanelBackgroundColor));
            template = template.Replace("{ACCENT_COLOR}", ColorToRgba(theme.AccentColor));
            template = template.Replace("{ACCENT_ALT_COLOR}", ColorToRgba(theme.AccentAltColor));
            template = template.Replace("{BTN_COLOR}", ColorToRgba(theme.ButtonColor));
            template = template.Replace("{BTN_HOVER_COLOR}", ColorToRgba(theme.ButtonHoverColor));
            template = template.Replace("{TEXT_COLOR}", ColorToRgba(theme.TextColor));
            
            // Write out the current theme CSS
            var guids = AssetDatabase.FindAssets("CurrentTheme t:StyleSheet");
            if (guids.Length > 0) {
                string currentThemePath = AssetDatabase.GUIDToAssetPath(guids[0]);
                string absolutePath = Path.GetFullPath(currentThemePath);
                File.WriteAllText(absolutePath, template);
            }
        }
    }
}
